const config = {
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  checkIgnorePragma: false,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  requirePragma: false,
  semi: true,
  singleAttributePerLine: false,
  singleQuote: true,
  trailingComma: 'all',
  useTabs: false,
  vueIndentScriptAndStyle: false,
  printWidth: 80,
  tabWidth: 2,
  rangeStart: 0,
  rangeEnd: Infinity,
  objectWrap: 'preserve',
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};

export default config;
